# -*- coding: utf-8 -*-
"""preprocessing_training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17eZWwEsFbwSAoo0zEifKRT9XUNFvQkEf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Carga de datos
df_carga = pd.read_csv('df_carga_total.csv')
df_eventos = pd.read_csv('df_eventos_total.csv')

# Conversión a datetime
df_carga['TIMESTAMP'] = pd.to_datetime(df_carga['TIMESTAMP'])
df_eventos['TIMESTAMP'] = pd.to_datetime(df_eventos['TIMESTAMP'])

# Ordenamiento cronológico por locación
df_carga = df_carga.sort_values(['LOCACION', 'TIMESTAMP'])
df_eventos = df_eventos.sort_values(['LOCACION', 'TIMESTAMP'])

plt.figure(figsize=(15, 6))
sns.boxplot(data=df_carga, x='LOCACION', y='IA')
plt.xticks(rotation=45)
plt.title('Distribución de Corriente Fase A por Locación')
plt.show()

# Ejemplo para una locación específica
loc_interes = 'MI PERU'
corr = df_carga[df_carga['LOCACION'] == loc_interes][['IA', 'IB', 'IC', 'IG', 'VAB', 'MW3', 'PF3']].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title(f'Correlación Eléctrica en {loc_interes}')
plt.show()

df_carga['diff_time'] = df_carga.groupby('LOCACION')['TIMESTAMP'].diff()
huecos = df_carga[df_carga['diff_time'] > pd.Timedelta(minutes=15)]
print(f"Se encontraron {len(huecos)} saltos en la telemetría.")

import matplotlib.dates as mdates

df_carga['TIMESTAMP'] = pd.to_datetime(df_carga['TIMESTAMP'])
df_eventos['TIMESTAMP'] = pd.to_datetime(df_eventos['TIMESTAMP'])

df_carga['ANIO_MES'] = df_carga['TIMESTAMP'].dt.to_period('M')
df_eventos['ANIO_MES'] = df_eventos['TIMESTAMP'].dt.to_period('M')

dispo_matrix = df_carga.groupby(['LOCACION', 'ANIO_MES']).size().unstack(fill_value=0)

plt.figure(figsize=(16, 8))
sns.heatmap(dispo_matrix, annot=True, fmt="d", cmap="YlGnBu", cbar_kws={'label': 'Loading logs'})
plt.title("", fontsize=14, pad=20)
plt.xlabel("Month-Year")
plt.ylabel("Recloser location")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print("\n" + "="*40)
print("REPORTE DE CALIDAD DE DATOS (DATA UPTIME)")
print("="*40)

total_esperado_mes = 2880
resumen_calidad = dispo_matrix.mean(axis=1).sort_values(ascending=False)

print("Promedio de registros mensuales por locación:")
print(resumen_calidad)

carga_total_mes = df_carga.groupby('ANIO_MES').size()
trips_total_mes = df_eventos[df_eventos['EVENT_STD'] == 'TRIP'].groupby('ANIO_MES').size()

fechas_x = carga_total_mes.index.to_timestamp()

fig, ax1 = plt.subplots(figsize=(14, 6))

ax1.plot(fechas_x, carga_total_mes.values, color='#1f77b4', marker='o', linewidth=2, label='Volumen Carga')
ax1.set_xlabel('Línea de Tiempo')
ax1.set_ylabel('N° Registros de Carga (Mensajes)', color='#1f77b4', fontsize=12)
ax1.tick_params(axis='y', labelcolor='#1f77b4')
ax1.grid(True, alpha=0.3)

ax2 = ax1.twinx()
trips_plot = trips_total_mes.reindex(carga_total_mes.index, fill_value=0)
ax2.bar(fechas_x, trips_plot.values, color='red', alpha=0.4, width=15, label='Fallas (TRIP)')
ax2.set_ylabel('N° de Fallas Reales', color='red', fontsize=12)
ax2.tick_params(axis='y', labelcolor='red')

plt.title("", fontsize=14)
fig.tight_layout()
plt.show()

stats_por_loc = df_carga.groupby('LOCACION')[['IA', 'IB', 'IC', 'IG', 'VAB']].agg(['mean', 'std', 'max'])
print("Estadísticos por Locación:")
print(stats_por_loc)

plt.figure(figsize=(15, 7))
sns.boxplot(data=df_carga, x='LOCACION', y='IG')
plt.yscale('log') # Escala logarítmica para ver mejor las fugas pequeñas
plt.xticks(rotation=45)
plt.title("Dispersión de Corriente de Tierra (IG) por Recloser - Escala Log")
plt.grid(True, alpha=0.3)
plt.show()

for loc in ['MI PERU', 'PUNO PAUCARCOLLA']:
    plt.figure(figsize=(6, 4))
    corr = df_carga[df_carga['LOCACION'] == loc][['IA', 'IG', 'VAB', 'PF3']].corr()
    sns.heatmap(corr, annot=True, cmap='coolwarm')
    plt.title(f"Matriz de Correlación: {loc}")
    plt.show()

"""# **PREPROCESAMIENTO**

**Reasoning**:
The previous attempt failed because `df_carga` was not defined in the current execution environment, as indicated by the `NameError`. To fix this, the dataframes `df_carga` and `df_eventos` need to be loaded and preprocessed from the beginning of the notebook to ensure they are available before calculating missing values.
"""

import pandas as pd

# Carga de datos (re-executing from the first cell to ensure df_carga is defined)
df_carga = pd.read_csv('df_carga_total.csv')
df_eventos = pd.read_csv('df_eventos_total.csv')

# Conversión a datetime
df_carga['TIMESTAMP'] = pd.to_datetime(df_carga['TIMESTAMP'])
df_eventos['TIMESTAMP'] = pd.to_datetime(df_eventos['TIMESTAMP'])

# Ordenamiento cronológico por locación
df_carga = df_carga.sort_values(['LOCACION', 'TIMESTAMP'])
df_eventos = df_eventos.sort_values(['LOCACION', 'TIMESTAMP'])

# Calculate and display missing values for df_carga
missing_values = df_carga.isnull().sum()
print("Missing values per column in df_carga:\n", missing_values)

# Calculate and display missing values for df_carga
missing_values2 = df_eventos.isnull().sum()
print("\n Missing values per column in df_carga:\n", missing_values2)

print("\n--- Analyzing df_eventos columns: CURR, GRP, SHOT ---")
print("\nData Types and Non-Null Counts for df_eventos[['CURR', 'GRP', 'SHOT']]:")
df_eventos[['CURR', 'GRP', 'SHOT']].info()

print("\nDescriptive Statistics for df_eventos[['CURR', 'GRP', 'SHOT']]:")
print(df_eventos[['CURR', 'GRP', 'SHOT']].describe())

print("\nUnique Values and Counts for df_eventos['GRP']:")
print(df_eventos['GRP'].value_counts())

print("\nUnique Values and Counts for df_eventos['SHOT']:")
print(df_eventos['SHOT'].value_counts())

print("\nMissing Values for df_eventos[['CURR', 'GRP', 'SHOT']]:")
print(df_eventos[['CURR', 'GRP', 'SHOT']].isnull().sum())

print("\n--- Analyzing df_carga column: 3I2 ---")
print("\nData Type and Non-Null Count for df_carga['3I2']:")
df_carga[['3I2']].info()

print("\nDescriptive Statistics for df_carga['3I2']:")
print(df_carga['3I2'].describe())

print("\nUnique Values and Counts for df_carga['3I2'] (top 20 if many):")
print(df_carga['3I2'].value_counts().head(20))

print("\nMissing Values for df_carga['3I2']:")
print(df_carga['3I2'].isnull().sum())

import numpy as np

# --- Imputation for df_carga ---
# Impute other identified missing value columns (IA, IB, IC, IG, VAB, VBC, VCA, FREQ, MW3, MVAR3, PF3) with their respective means.
for col in ['IA', 'IB', 'IC', 'IG', 'VAB', 'VBC', 'VCA', 'FREQ', 'MW3', 'MVAR3', 'PF3']:
    if df_carga[col].isnull().any():
        df_carga[col] = df_carga[col].fillna(df_carga[col].mean())

# --- Feature Engineering from df_eventos for df_carga ---
# Aggregate event features within a 24-hour window before each df_carga timestamp

def aggregate_event_features(df_carga_row, df_eventos):
    locacion = df_carga_row['LOCACION']
    timestamp = df_carga_row['TIMESTAMP']

    # Define the 24-hour window before the current df_carga timestamp
    window_start = timestamp - pd.Timedelta(hours=24)

    # Filter events for the specific location and within the 24-hour window
    relevant_events = df_eventos[(
        (df_eventos['LOCACION'] == locacion) &
        (df_eventos['TIMESTAMP'] < timestamp) &
        (df_eventos['TIMESTAMP'] >= window_start)
    )]

    # Initialize features
    features = {
        'EVENT_COUNT_24H': 0,
        'MEAN_CURR_24H': 0.0,
        'MAX_CURR_24H': 0.0,
        'STD_CURR_24H': 0.0,
        'GRP_1_COUNT_24H': 0,
        'GRP_2_COUNT_24H': 0,
        'SHOT_0_COUNT_24H': 0,
        'SHOT_1_COUNT_24H': 0,
        'SHOT_2_COUNT_24H': 0,
        'SHOT_3_COUNT_24H': 0
    }

    if not relevant_events.empty:
        features['EVENT_COUNT_24H'] = len(relevant_events)
        if 'CURR' in relevant_events.columns and relevant_events['CURR'].notna().any():
            features['MEAN_CURR_24H'] = relevant_events['CURR'].mean()
            features['MAX_CURR_24H'] = relevant_events['CURR'].max()
            features['STD_CURR_24H'] = relevant_events['CURR'].std()

        features['GRP_1_COUNT_24H'] = (relevant_events['GRP'] == 1).sum()
        features['GRP_2_COUNT_24H'] = (relevant_events['GRP'] == 2).sum()
        features['SHOT_0_COUNT_24H'] = (relevant_events['SHOT'] == 0).sum()
        features['SHOT_1_COUNT_24H'] = (relevant_events['SHOT'] == 1).sum()
        features['SHOT_2_COUNT_24H'] = (relevant_events['SHOT'] == 2).sum()
        features['SHOT_3_COUNT_24H'] = (relevant_events['SHOT'] == 3).sum()

    return pd.Series(features)

# Ensure df_carga and df_eventos are sorted by timestamp and locacion for efficient processing
df_carga = df_carga.sort_values(by=['LOCACION', 'TIMESTAMP']).reset_index(drop=True)
df_eventos = df_eventos.sort_values(by=['LOCACION', 'TIMESTAMP']).reset_index(drop=True)

# Initialize columns to avoid SettingWithCopyWarning and for proper assignment
for col_name in [
    'EVENT_COUNT_24H', 'MEAN_CURR_24H', 'MAX_CURR_24H', 'STD_CURR_24H',
    'GRP_1_COUNT_24H', 'GRP_2_COUNT_24H', 'SHOT_0_COUNT_24H',
    'SHOT_1_COUNT_24H', 'SHOT_2_COUNT_24H', 'SHOT_3_COUNT_24H'
]:
    df_carga[col_name] = 0.0 # Use float for all to handle potential NaNs from std() etc.

# Iterate by location to optimize event filtering
for loc in df_carga['LOCACION'].unique():
    loc_carga = df_carga[df_carga['LOCACION'] == loc].copy()
    loc_events = df_eventos[df_eventos['LOCACION'] == loc]

    # Using apply for now, but acknowledge performance for large datasets
    new_features = loc_carga.apply(lambda row: aggregate_event_features(row, loc_events), axis=1)

    # Update the original df_carga with the new features
    df_carga.loc[loc_carga.index, new_features.columns] = new_features

print(f"Updated df_carga shape: {df_carga.shape}")
print("New features added to df_carga:")
print(df_carga[[
    'EVENT_COUNT_24H', 'MEAN_CURR_24H', 'MAX_CURR_24H', 'STD_CURR_24H',
    'GRP_1_COUNT_24H', 'GRP_2_COUNT_24H', 'SHOT_0_COUNT_24H',
    'SHOT_1_COUNT_24H', 'SHOT_2_COUNT_24H', 'SHOT_3_COUNT_24H'
]].head())

"""**Reasoning**:
The subtask requires updating the feature selection for the models, and then re-training and evaluating them. I will first re-apply the preprocessing steps (robust normalization and creation of `DESBALANCE` and `VARIACION_V`) on the `df_carga` which now contains the imputed and new aggregated event features. Then, I will update the feature list to include these new features, re-split the data, and re-train and evaluate all models. Finally, I will display the updated comparative metrics and plots to assess the impact on performance.


"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# --- PASO 1: Clasificación de Severidad en Eventos (re-run to ensure df_eventos is prepared) ---
def clasificar_severidad(event_std):
    rojo = ['TRIP', 'BC_T', 'BG_T', 'ABC', 'AB_T', 'AG_T', 'CG_T', 'AC_T']
    amarillo = ['AB', 'CA', 'BC', 'AG', 'BG', 'CG', 'AC']
    if event_std in rojo: return 2
    if event_std in amarillo: return 1
    return 0

df_eventos['SEVERIDAD'] = df_eventos['EVENT_STD'].apply(clasificar_severidad)

# --- PASO 2: Normalización Robusta por Recloser (re-run with updated df_carga) ---
# Ensure original electrical variables are present before normalization
vars_to_norm = ['IA', 'IB', 'IC', 'IG', 'VAB', 'FREQ']
for var in vars_to_norm:
    mean_map = df_carga.groupby('LOCACION')[var].transform('mean')
    std_map = df_carga.groupby('LOCACION')[var].transform('std')
    df_carga[f'{var}_Z'] = (df_carga[var] - mean_map) / (std_map + 1e-6)

# --- PASO 3: Ingeniería de Features Eléctricas (re-run with updated df_carga) ---
df_carga['DESBALANCE'] = df_carga[['IA_Z', 'IB_Z', 'IC_Z']].std(axis=1)
df_carga['VARIACION_V'] = df_carga.groupby('LOCACION')['VAB_Z'].diff().fillna(0)

# --- PASO 4: Generación del Target (Ventana 24h) (re-run to ensure consistency) ---
fallas_criticas = df_eventos[df_eventos['SEVERIDAD'] == 2].copy()
df_carga['TARGET'] = 0
for loc in df_carga['LOCACION'].unique():
    timestamps_falla = fallas_criticas[fallas_criticas['LOCACION'] == loc]['TIMESTAMP']
    for t_falla in timestamps_falla:
        mask = (df_carga['LOCACION'] == loc) & \
               (df_carga['TIMESTAMP'] < t_falla) & \
               (df_carga['TIMESTAMP'] >= t_falla - pd.Timedelta(hours=24))
        df_carga.loc[mask, 'TARGET'] = 1

print(f"Dataset Preprocesado con nuevas features:")
print(f"Total registros: {len(df_carga)}")
print(f"Registros positivos (Pre-falla): {df_carga['TARGET'].sum()}")

# 1. Selección de variables (Features) y Objetivo (Target) - UPDATED
# Include new event-related features and the normalized 3I2
features = [
    'IA_Z', 'IB_Z', 'IC_Z', 'IG_Z', 'VAB_Z', 'FREQ_Z',
    'DESBALANCE', 'VARIACION_V',
    'EVENT_COUNT_24H', 'MEAN_CURR_24H', 'MAX_CURR_24H', 'STD_CURR_24H',
    'GRP_1_COUNT_24H', 'GRP_2_COUNT_24H', 'SHOT_0_COUNT_24H',
    'SHOT_1_COUNT_24H', 'SHOT_2_COUNT_24H', 'SHOT_3_COUNT_24H'
]
X = df_carga[features].fillna(0) # XGBoost handles nulos, but for KNN/SVM we impute with 0 (as it's mean in Z-score)
y = df_carga['TARGET']

# Split cronológico (80% tren, 20% test)
split_idx = int(len(X) * 0.8)
X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

# 2. Definición de Modelos (re-initialize to ensure fresh training)
models = {
    "Decision Tree": DecisionTreeClassifier(max_depth=5, class_weight='balanced'),
    "Random Forest": RandomForestClassifier(n_estimators=100, max_depth=5, class_weight='balanced', n_jobs=-1),
    "XGBoost": XGBClassifier(scale_pos_weight=(len(y_train)-sum(y_train))/sum(y_train), max_depth=5, use_label_encoder=False, eval_metric='logloss'),
    "KNN": KNeighborsClassifier(n_neighbors=5),
}

results = {}
plt.figure(figsize=(10, 8))

# 3. Entrenamiento y Evaluación
for name, model in models.items():
    print(f"Entrenando {name} con nuevas features...")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    # Métricas
    results[name] = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, zero_division=0),
        "Recall": recall_score(y_test, y_pred, zero_division=0),
        "F1": f1_score(y_test, y_pred, zero_division=0),
        "ROC AUC": roc_auc_score(y_test, y_proba)
    }

    # Curva ROC
    fpr, tpr, _ = roc_curve(y_test, y_proba)
    plt.plot(fpr, tpr, label=f'{name} (AUC = {results[name]["ROC AUC"]:.2f})')

plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('')
plt.legend()
plt.show()

# 4. Tabla de resultados
df_res = pd.DataFrame(results).T
print("\nCUADRO COMPARATIVO DE MÉTRICAS (con nuevas features):")
print(df_res)

# --- LSTM Model Training and Evaluation (Re-run) ---

# 1. Preparación de secuencias para LSTM (Ventanas de 8 registros = 2 horas)
def create_sequences(X, y, time_steps=8):
    Xs, ys = [], []
    for i in range(len(X) - time_steps):
        Xs.append(X.iloc[i:(i + time_steps)].values)
        ys.append(y.iloc[i + time_steps])
    return np.array(Xs), np.array(ys)

X_train_seq, y_train_seq = create_sequences(X_train, y_train)
X_test_seq, y_test_seq = create_sequences(X_test, y_test)

# 2. Arquitectura de la Red Neuronal (re-define for fresh training)
model_lstm = Sequential([
    LSTM(64, input_shape=(X_train_seq.shape[1], X_train_seq.shape[2]), return_sequences=True),
    Dropout(0.2),
    LSTM(32),
    Dropout(0.2),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

model_lstm.compile(optimizer='adam', loss='binary_crossentropy', metrics=['AUC'])

# 3. Entrenamiento (con pesos para manejar el desbalance)
class_weights = {0: 1, 1: 15} # Penalizamos 15 veces más el perder una falla
print("\nEntrenando LSTM con nuevas features...")
history = model_lstm.fit(X_train_seq, y_train_seq, epochs=10, batch_size=64,
                    validation_split=0.1, class_weight=class_weights, verbose=1)

# Agregar resultados de LSTM a la tabla (calculando métricas post-entrenamiento)
y_proba_lstm = model_lstm.predict(X_test_seq)
y_pred_lstm_binary = (y_proba_lstm > 0.5).astype(int)

lstm_metrics = {
    "Accuracy": accuracy_score(y_test_seq, y_pred_lstm_binary),
    "Precision": precision_score(y_test_seq, y_pred_lstm_binary, zero_division=0),
    "Recall": recall_score(y_test_seq, y_pred_lstm_binary, zero_division=0),
    "F1": f1_score(y_test_seq, y_pred_lstm_binary, zero_division=0),
    "ROC AUC": roc_auc_score(y_test_seq, y_proba_lstm)
}

# Add LSTM results to the existing results dictionary
results['LSTM'] = lstm_metrics

# Update the comparative DataFrame
df_res = pd.DataFrame(results).T

print("\nCUADRO COMPARATIVO DE MÉTRICAS FINAL (con nuevas features):")
print(df_res)

# Plot Recall Comparison
plt.figure(figsize=(10, 6))
df_res['Recall'].sort_values().plot(kind='barh', color='skyblue')
plt.title('')
plt.xlabel('Puntaje Recall')
plt.show()

# Plot ROC curve for LSTM along with others (re-plot all for consistency)
plt.figure(figsize=(10, 8))
for name, model_metrics in results.items():
    if name == 'LSTM':
        fpr_lstm, tpr_lstm, _ = roc_curve(y_test_seq, y_proba_lstm)
        plt.plot(fpr_lstm, tpr_lstm, label=f'{name} (AUC = {model_metrics["ROC AUC"]:.2f})')
    else:
        model = models[name]
        if name in models: # Check if it's a scikit-learn model
            y_proba_other = models[name].predict_proba(X_test)[:, 1]
            fpr_other, tpr_other, _ = roc_curve(y_test, y_proba_other)
            plt.plot(fpr_other, tpr_other, label=f'{name} (AUC = {model_metrics["ROC AUC"]:.2f})')
        else:
            plt.plot([], [], label=f'{name} (AUC = {model_metrics["ROC AUC"]:.2f})', linestyle='-') # Fallback if model not in 'models' dict

plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Asegurémonos de tener el modelo de Decision Tree disponible
best_model_dt = models['Decision Tree']

# Realizamos predicciones sobre el conjunto de prueba
y_pred_dt = best_model_dt.predict(X_test)

# Creamos un DataFrame para comparar las predicciones con los valores reales
predictions_comparison = pd.DataFrame({
    'Real': y_test.values,
    'Predicción_DecisionTree': y_pred_dt
})

# Seleccionamos un segmento para visualizar (por ejemplo, los primeros 500 puntos del test set)
# Puedes ajustar el rango (ej. 1000:1500) para ver diferentes secciones
segment_start = 0
segment_end = 500
comparison_subset = predictions_comparison.iloc[segment_start:segment_end]

plt.figure(figsize=(15, 6))
plt.plot(comparison_subset.index, comparison_subset['Real'], label='Real (TARGET)', color='blue', linewidth=2)
plt.scatter(comparison_subset.index, comparison_subset['Predicción_DecisionTree'], label='Predicción Decision Tree', color='red', marker='x', s=50, alpha=0.6)
plt.title('Comparación de Predicciones del Modelo Decision Tree vs Valores Reales')
plt.xlabel('Índice de Muestra en el Conjunto de Prueba')
plt.ylabel('Valor (0: No Falla, 1: Falla)')
plt.yticks([0, 1])
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Seleccionamos el modelo Decision Tree
best_model_dt = models['Decision Tree']

# Realizamos predicciones sobre el conjunto de prueba
y_pred_dt = best_model_dt.predict(X_test)

# Creamos un DataFrame para comparar las predicciones con los valores reales
predictions_df = pd.DataFrame({
    'Real': y_test.values,
    'Predicción_DecisionTree': y_pred_dt
})

print("Primeras 20 Predicciones del Modelo Decision Tree vs Valores Reales:")
print(predictions_df.head(20))

import shap
import matplotlib.pyplot as plt

# Seleccionamos el modelo Decision Tree
best_model = models['Decision Tree']

# Crear un 'explainer' para el modelo Decision Tree
explainer = shap.TreeExplainer(best_model)

# Calcular los valores SHAP para el conjunto de prueba
# shap_values es una lista de arrays para cada clase.
# Para clasificación binaria, shap_values es un array 3D: (num_samples, num_features, num_classes)
shap_values = explainer.shap_values(X_test)

# Visualizar la importancia de las características (summary plot)
# Para clasificación binaria, shap_values[:, :, 1] representa los SHAP values para la clase positiva (TARGET=1)
shap.summary_plot(shap_values[:, :, 1], X_test, plot_type="bar", show=False)
plt.title("Importancia de Características SHAP (Decision Tree)")
plt.tight_layout()
plt.show()

# Visualizar el impacto de una característica específica (dependence plot)
# Por ejemplo, para 'IA_Z'
shap.dependence_plot("IA_Z", shap_values[:, :, 1], X_test, show=False)
plt.title("SHAP Dependence Plot para IA_Z (Decision Tree)")
plt.tight_layout()
plt.show()